douban:
  api_key: 0ce4a109569fb71726ade31c03df2545
  api_key_secret: 7d5e9f860747891c
  site: http://www.douban.com
  request_token_path: /service/auth/request_token
  access_token_path: /service/auth/access_token
  authorize_path: /service/auth/authorize
  signature_method: HMAC-SHA1
  scheme: header
  realm: http//localhost:3000/
