sina:
  api_key: 2194565976
  api_key_secret: 4fee79728adb347e0428ce5a7394eff6
  site: http://api.t.sina.com.cn
  request_token_path: /oauth/request_token
  access_token_path: /oauth/access_token
  authorize_path: /oauth/authorize
  signature_method: HMAC-SHA1
  scheme: header
  realm: http//localhost:3000/
